"""empty message

Revision ID: c6ce728411e4
Revises: 12e1949468b0
Create Date: 2024-09-26 22:59:29.027311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ce728411e4'
down_revision: Union[str, None] = '12e1949468b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('id_orders', sa.Integer(), nullable=False))
    op.add_column('order_items', sa.Column('id_products', sa.Integer(), nullable=False))
    op.drop_constraint('order_items_id_product_fkey', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_id_order_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'products', ['id_products'], ['id'])
    op.create_foreign_key(None, 'order_items', 'orders', ['id_orders'], ['id'])
    op.drop_column('order_items', 'id_product')
    op.drop_column('order_items', 'id_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('id_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('id_product', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_id_order_fkey', 'order_items', 'orders', ['id_order'], ['id'])
    op.create_foreign_key('order_items_id_product_fkey', 'order_items', 'products', ['id_product'], ['id'])
    op.drop_column('order_items', 'id_products')
    op.drop_column('order_items', 'id_orders')
    # ### end Alembic commands ###
